name: CI-Pacman

on:
  push:
    branches: [ main, FTR-actions ]
  pull_request:
    branches: [ main, FTR-actions ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk
    steps:
      - uses: actions/checkout@v2

      - name: Info
        run: |
          javac -version
          java -version

      - name: Compile src files
        working-directory: Projects/P1
        run: javac -cp "src/" src/*.java

      - name: Compile test files
        working-directory: Projects/P1
        run: javac -cp "tests/junit-4.10.jar:src/:tests/" tests/*.java

  test-pacman-consume:
    runs-on: ubuntu-latest
    container:
      image: openjdk
    steps:
      - uses: actions/checkout@v2

      - name: Info
        run: |
          javac -version
          java -version

      - name: Compile files for test
        working-directory: Projects/P1
        run: javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestConsume.java

      - name: Run test
        working-directory: Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestConsume

  test-ghost-attack:
    runs-on: ubuntu-latest
    container:
      image: openjdk
    steps:
      - uses: actions/checkout@v2

      - name: Info
        run: |
          javac -version
          java -version

      - name: Compile files for test
        working-directory: Projects/P1
        run: javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestAttack.java

      - name: Run test
        working-directory: Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestAttack

  test-map-eatcookie:
    runs-on: ubuntu-latest
    container:
      image: openjdk
    steps:
      - uses: actions/checkout@v2

      - name: Info
        run: |
          javac -version
          java -version

      - name: Compile files for test
        working-directory: Projects/P1
        run: javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestMapEatCookie.java

      - name: Run test
        working-directory: Projects/P1
        run: java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapEatCookie

